name: Lighthouse Audit

on:
  push:
    branches:
      - main

jobs:
  lighthouse-ci:
    name: Run Lighthouse checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse audit
        run: |
          lhci autorun --url="//http://sandhya-project-cicd.s3-website.ap-south-1.amazonaws.com/"